### ISSUE TITLE
Release Roadmap

### ISSUE THREAD

**Issue by jkeam** [skellock/apisauce#101]
I was just curious on what the roadmap for this project is.  Ideas on new version release dates as well as what is planned for each release?

Also wanted to say I appreciate and really like all the hard work put into this proj :)

**Comment by skellock** [comment]
Heyo!  Thank you!  That's nice to hear.

To be honest, there isn't a roadmap for this project.  We wrap [axios](https://github.com/mzabriskie/axios) and provide a small set of opinions on top.

We'll go wherever they go.  =)

I'm all ears if you have something specific in mind though.
