### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by JPeer264** [skellock/apisauce#103]
What is new in `0.12.0`? I already found it out by reading the commits, but I guess it is also good for others who trust on the changelog.

**Comment by skellock** [comment]
Thank you for the reminder.  I missed that entirely.

**Comment by skellock** [comment]
Thanks again @JPeer264 .

https://github.com/skellock/apisauce/commit/d8e0fa3e197e90dbc80a72f933119d6926c8d07e
