### ISSUE TITLE
Cannot pass body in DELETE

### ISSUE THREAD

**Issue by kumarpatel** [skellock/apisauce#105]
Is there a reason for this?

[delete: partial(doRequestWithoutBody, ['delete'])](https://github.com/skellock/apisauce/blob/939deafeafe1d984416e517b1a9838962826968c/lib/apisauce.js#L338)

If so, any way to override it in this one instance?

The API endpoint I'm working with accepts body for DELETE. not query params. :(

**Comment by skellock** [comment]
Ya, the 3rd parameter can override everything.  That will be the `config` object sent to `axios`.  Does that work?

**Comment by kumarpatel** [comment]
Works!! Thanks.

**Comment by manjeets12** [comment]
@kumarpatel @skellock  can you please post some working code, I am not able to get away with this.

I am trying this
 `return tokens.serviceUrl.delete(url, {}, params);`
where tokens.serviceUrl is 

```
this.serviceUrl = create({
         baseURL: myApiurl
    });
```

**Comment by Chatharaju** [comment]
Try this: 
tokens.serviceUrl.delete(url,  {}, {data: yourPaload, anyOtherParameters}); 

Think this should be helpful.

**Comment by manjeets12** [comment]
@chatharaju it works, so it is just that we have to override data parameter

**Comment by Chatharaju** [comment]
Yes, your third parameter can override everything.

**Comment by hungdev** [comment]
@Chatharaju thanks you so much. It worked for me.

**Comment by manjuy124** [comment]
@Chatharaju thanks! It worked.
