### ISSUE TITLE
Multiple concurent requests in apisauce

### ISSUE THREAD

**Issue by kidnapkin** [skellock/apisauce#106]
Is there any way to chain requests like axios does it?

```JavaScript
function getUserAccount() {
  return axios.get('/user/12345');
}

function getUserPermissions() {
  return axios.get('/user/12345/permissions');
}

axios.all([getUserAccount(), getUserPermissions()])
  .then(axios.spread(function (acct, perms) {
    // Both requests are now complete
  }));
```
I found this feature very useful when fetching from multiple endpoints.
Can I do something similar with awesome apisauce?

**Comment by skellock** [comment]
Nothing built in.

I haven't used `all` and `spread` before.  Any different than `Promise.all()`?

[p-all](https://github.com/sindresorhus/p-all) looks good too.

Lemme know what you settle on.  I'm interested as well.
