### ISSUE TITLE
POST says NETWORK_ERROR when file uri is invalid

### ISSUE THREAD

**Issue by iorena** [skellock/apisauce#107]
Using the code below
```
const uploadImage = ({url}, uri) => {
    const api = apisauce.create({
      baseURL: url,
      headers: {
        'Cache-Control': 'no-cache',
        'Content-Type': 'multipart/form-data'
      },
      timeout: 10000
    })
    const formData = new FormData()
    formData.append('file', {
      uri,
      type: 'image/jpeg',
      name: 'image'
    })
    api.post('/', formData).then((res) => console.log(res))
```
Uri was undefined. Response prints out as 

> {
>   duration: 33,
>   problem: 'NETWORK_ERROR',
>   ok: false,
>   status: null,
>   headers: null,
>   ...

Using apisauce version 0.10.0

**Comment by skellock** [comment]
What does your `uri` look like coming into that function?

What does your server logs show?  That the data isn't being passed along?

Also, that content-type doesn't look right, axios will set that properly for us.

**Comment by chiechelski** [comment]
Hi @skellock ,
I am having a similar issue using apisauce on my react native project. I even tried different versions but it does not want to work anymore :(. I might be missing some other configuration as it works on my iphone device and on the simulator, just not on my android device.
```
Error: Network Error
    at createError (createError.js:15)
    at XMLHttpRequest.handleError (xhr.js:87)
    at XMLHttpRequest.dispatchEvent (event-target.js:172)
    at XMLHttpRequest.setReadyState (XMLHttpRequest.js:542)
    at XMLHttpRequest.__didCompleteResponse (XMLHttpRequest.js:378)
    at XMLHttpRequest.js:482
    at RCTDeviceEventEmitter.emit (EventEmitter.js:181)
    at MessageQueue.__callFunction (MessageQueue.js:242)
    at MessageQueue.js:108
    at guard (MessageQueue.js:46)
```
Any idea where to look at? I will keep debugging until I found the issue.
Thanks in advance.

**Comment by skellock** [comment]
Bummer. What version of react native are you using?  What version of android? Thx.

**Comment by chiechelski** [comment]
Hey @skellock thanks for your reply and awesome work with apisauce.
Sorry, I should have posted this last night, but I was actually able to fix the issue and it was related o a misconfiguration on my https nodejs server :(
I used this URL to test if my certificate was correctly installed https://developer.android.com/training/articles/security-ssl.html in case someone has a similar issue.
Thanks again.
Cheers

**Comment by skellock** [comment]
Sweet. Thx for the follow up. 🎉

**Comment by iorena** [comment]
Uri was undefined when I got this error. Server didn't receive the call at all. Content-Type doesn't affect the problem. Of course I can pretty easily see my mistake, but the error message is misleading.
