### ISSUE TITLE
One of the sources for assign has an enumerable key on the prototype chain

### ISSUE THREAD

**Issue by pjamrozowicz** [skellock/apisauce#108]
Hi!

After updating React Native to the latest version (0.45.1) I started getting an error:

> One of the sources for assign has an enumerable key on the prototype chain. Are you trying to assign a prototype property? We don't allow it, as this is an edge case that we do not support. This error is a performance optimization and not spec compliant.

I tracked it down and it seems that apisauce is causing it - when I take out the import to apisauce library my project works fine. What is weird, it happens only in iOS, on Android there is no such error.

This is the screenshot from iOS simulator.

![screenshot_1](https://user-images.githubusercontent.com/10074468/27151866-3b4bdc02-514c-11e7-89a0-c03d07ab059d.png)

I added a console log inside Object.es6.js and this is where it returns an error:

![screenshot_2](https://user-images.githubusercontent.com/10074468/27151920-66cf7eec-514c-11e7-9f30-75be5aaeb5bc.png)

Is it React Native bug or is there anything I can do to make it work and use apisauce in my iOS project?

**Comment by skellock** [comment]
Oh wow.  That’s an interesting one.  I haven’t seen that yet.

Are you able to reproduce this outside your project?  I could track it down a little easier.

What versions of everything are your using? The latest Apisauce? And it’s just the fact you’re importing it that breaks things eh?  So strange.

**Comment by pjamrozowicz** [comment]
@skellock Yes, simple import breaks things.

**macOS**: MacOS Sierra 10.12.5
**Xcode**: 8.3.3
**yarn**: 0.24.6
**simulator**: iPhone 6 iOS 10.3

**Steps:**
`react-native init MyProject`
`npm i apisauce --save`
add:
`import apisauce from 'apisauce';`
inside index.ios.js

package.json file looks like this:

```
{
  "name": "MyProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "apisauce": "^0.13.0",
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "2.0.0",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by amardeepranu** [comment]
Also getting this exact error after updating React Native to the latest version (0.45.1)

**Comment by skycomdeveloper** [comment]
+1, the same issue on React 0.45.1

`import apisauce from 'apisauce'`

crashes an application

**Comment by godness84** [comment]
+1, the same issue on React 0.45.1

Even on Android

**Comment by skellock** [comment]
Ok folks.  `apisauce@0.14.0` is now available.  Would you mind giving that a go?  Please lemme know if that's working for ya.

I've tested here on `0.45.1` and with `create-react-app`.

**Comment by godness84** [comment]
It works! thank you very much!

**Comment by pjamrozowicz** [comment]
Works for me too, thank you for the quick fix!

**Comment by skellock** [comment]
Sweet!

**Comment by alexmngn** [comment]
I still have the same problem, and I use exactly the same version of apisauce and react-native. Can we have more info about what is the issue?

**Comment by godness84** [comment]
Did you try with a clean project with just react-native and apisauce? Maybe the problem is on some other libraries.

**Comment by alexmngn** [comment]
@godness84 I am running it from a clean project, although I have 2 separates repo:

- MainApp which requires RN 0.45.1
- ServiceApp which requires apisauce 0.14.0

MainApp imports ServiceApp. There isn't much more than apisauce in it... and the error is thrown when I import apisauce.

**Comment by godness84** [comment]
Sorry but I don't know how to help you. Anyway it would be useful for anybody else to have a github repo with your code in order to debug it.

**Comment by alexmngn** [comment]
I downgraded to RN 0.44, react 16 alpha 6 and apisauce 0.13, works now.
