### ISSUE TITLE
Api sauce doesn't get full list of HTTP header fields

### ISSUE THREAD

**Issue by ningo-agilityio** [skellock/apisauce#110]
Api sauce doesn't get full list of HTTP header fields.
You can check the list [here](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields).

For now, I only get 4 fields: 
```
cache-control:"no-cache, no-store, max-age=0, must-revalidate"
content-type:"application/json;charset=UTF-8"
expires:"0"
pragma:"no-cache"
```
Do I miss any configuration to see full of list?

**Comment by skellock** [comment]
You should get what the server sends you. Are you experiencing a situation where the server is sending you more when you use curl or postman?

**Comment by ningo-agilityio** [comment]
I checked from `swagger` for header's response & this is the result:
```
{
  "pragma": "no-cache",
  "date": "Sat, 24 Jun 2017 16:05:12 GMT",
  "x-content-type-options": "nosniff",
  "x-frame-options": "DENY",
  "access-control-allow-methods": "POST, GET, OPTIONS, DELETE, PUT, PATCH",
  "content-type": "application/json;charset=UTF-8",
  "access-control-max-age": "3600",
  "cache-control": "no-cache, no-store, max-age=0, must-revalidate",
  "transfer-encoding": "chunked",
  "access-control-allow-credentials": "true",
  "access-control-allow-headers": "Content-Type, Accept, X-Requested-With, Authorization",
  "x-xss-protection": "1; mode=block",
  "x-total-count": "25",
  "expires": "0"
}
```
But apisauce only returns to me only 4 fields `cache-control`, `content-type`, `expires`, `pragma`.
Have you faced this issue yet?

**Comment by skellock** [comment]
I haven’t see this issue, no.  Are you getting the right data back in your API? Are you using react-native? Android?

**Comment by ningo-agilityio** [comment]
I only use pure React.
```
export const API = create({
  baseURL: 'http://localhost:8080'
});
```

```
const response = yield call(() => API.post(
      '/api/v1/users',
      {
        user: action.user,
        ...new FormData('profile', action.profile)
      },
      {
        headers: {
          Authorization: token
        }
      }
    ));
```

**Comment by skellock** [comment]
When that response comes back, I know the headers aren’t all there, but does the right data appear? Looks like you might be creating a new user in your example.  Does the server create it ok? Does it send back data you can see ok?

**Comment by skellock** [comment]
Another thing to check is the `response.config` object.  This contains the request that `axios` sent. Do all the outbound headers look right to you?

**Comment by ningo-agilityio** [comment]
Yup. New user is creating successfully. But I can't full of response headers.

**Comment by skellock** [comment]
Does this only happen with that end-point?  Or do you see different headers for a GET to a use 9for example)?

Does that end-point redirect after posting?  Or is it a straight-up 200?

You should be able to verify this in your chrome debugger on the network tab.

Thanks for bearing with me.  This is a scooby doo mystery.

**Comment by ningo-agilityio** [comment]
This happens to all my endpoints.
It is a straight up 200.
I did verify on chrome debugger & see full of headers list.
But get by apisauce only return 4 above fields.

**Comment by skellock** [comment]
Ok, this sounds like a CORS concern. 

Are you able to add the headers you would like to read in your list `"access-control-allow-headers": "Content-Type, Accept, X-Requested-With, Authorization"`?

CORS is a security thing.

More info https://stackoverflow.com/questions/37897523/axios-get-access-to-response-header-fields

Could this be it?

**Comment by ningo-agilityio** [comment]
It worked. Thanks a bunch @skellock.

**Comment by skellock** [comment]
Sweet!
