### ISSUE TITLE
One request, two responses

### ISSUE THREAD

**Issue by jmeiss** [skellock/apisauce#113]
HI guys,

I'm facing an issue since yesterday that I can't solve by myself so I'm asking your help since I don't know if it's a bug or not.

I use apisauce v0.14.0 + react 16.0.0-alpha.6 + react-native 0.44.3 + redux-saga 0.15.3

I added some logs in `addRequestTransform` and `addResponseTransform`

From a saga, I call an endpoint from my API. I can see the right data passing by `addRequestTransform` and a correct response passing by `addResponseTransform`. The exact response I'm waiting for.

BUT I've a second response passing by `addResponseTransform` with a weird data:
```
{
    duration: 89,
    problem: 'UNKNOWN_ERROR',
    ok: false,
    status: null,
    headers: null,
    config: null,
    data: null
}
```

and so, that's the response received and processed by the saga which brings an unprocessable response.

When I google for `UNKNOWN_ERROR` the only occurence I find is in `apisauce` source code.

Does anyone has any idea of what could bring me to this error code?

Thanks for your help

**Comment by skellock** [comment]
Hmm...

Does the saga get called twice?

Are you using reactotron by any chance?  You can see every single network request with it (at the xmlhttprequest level)

Does this happen on requests that don't have a requestTransform?

`UNKNOWN_ERROR` is what apisauce uses when it can't deduce what the real underlying error is.

Are you testing this on a android 4.x emulator/device by any chance?

**Comment by jmeiss** [comment]
Thanks skellock for your questions.

The saga is not called twice because the request in made only once (I'm passing only once in `addRequestTransform` and I receive only one request on the API)

Yes I use reactotron and here is a screenshot of the logs
<img width="1009" alt="screen shot 2017-07-03 at 22 57 11" src="https://user-images.githubusercontent.com/227276/27807728-11c19164-6043-11e7-9fbb-a1b576772d6e.png">

All my requests and responses are passing by a requestTransform and a responseTransform which are:

```
  apiConfig.addRequestTransform(request => {
    // we check if the request is coming from API v0
    // we can remove that condition when all the endpoints use jsonapi.org convention
    if (request && request.url && request.url.includes('api/')) {
      return null
    }

    // Convert camelCase key to kebab-case key to match our API requirements
    if (request.data) {
      request.data = mapKeysDeep(request.data, (v, k) => _.kebabCase(k))
    }
  })

  apiConfig.addResponseTransform(response => {
    // we check if the response is coming from API v0
    // we can remove that condition when all the endpoints use jsonapi.org convention
    if (response &&
        response.headers &&
        !response.headers['content-type'].includes(response.config.headers['Accept'])) {
      return null
    }

    // normalize JSON API data for redux applications
    if (response.data) {
      response.data = normalize(response.data)
    }
  })
```

I'm testing in on an iOS emulator (iPhone 6 iOS 10.2) and a physical OnePlus 3T.

Any thought?

**Comment by skellock** [comment]
I see calls to `ASYNC_STORAGE` too.  Related?

Do all calls to your API have this double call behaviour?  

Is it possible to remove request transforms & response transforms from the equation?  (just for now).

**Comment by jmeiss** [comment]
Good point about the double `ASYNC_STORAGE` call.

It seams I always have a double `ASYNC_STORAGE setItem(reduxPersist:fooBar)` when I've a response from the API.

I removed all the request and response transforms (except the one for reactotron otherwise I can't see the `ASYNC_STORAGE` calls ;)

I would look into that direction to try to find where it could come from (redux-persist?) instead of inspecting for the `UNKNOWN_ERROR`.

I'm a month old newbie with react so if you have some hypothesis that could help me, they are more than welcome ;)

I will let you know how it goes. Thanks for pointing that (issue?)!

**Comment by skellock** [comment]
The order is kinda strange too. 

- Your action kicks off
- then your saga presumably starts triggering an api call
- the request transform kicks in
- then immediately two async storage events???

From the code you linked in that request transform, you don’t have any async storage code.

Do you have more than one request transform?

Is there more than one listener to the REGISTER_DEVICE_REQUEST action?

**Comment by jmeiss** [comment]
The AsyncStorage code is in the following saga when I fetch the device token with `yield call(PushNotification.getDeviceToken)`
```
export function * registerDevice (api) {
  yield call(PushNotification.requestPermissions)

  const token = yield call(PushNotification.getDeviceToken)
  const appVersion = DeviceInfo.getVersion()
  const lang = DeviceInfo.getDeviceLocale().substr(0, 2)
  const deviceUuid = DeviceInfo.getUniqueID()
  const devicePlatform = Platform.OS
  const deviceVersion = DeviceInfo.getSystemVersion()
  const deviceModel = DeviceInfo.getModel()
  const deviceManufacturer = DeviceInfo.getManufacturer()

  const response = yield call(api.registerDevice,
    appVersion,
    token,
    lang,
    deviceUuid,
    devicePlatform,
    deviceVersion,
    deviceModel,
    deviceManufacturer
  )

  if (response.ok) {
    yield put(NotificationActions.registerDeviceSuccess())
  } else {
    yield put(NotificationActions.registerDeviceFailure())
  }
}
```

`Do you have more than one request transform?`
=> yes, I've that one, scaffolded by ignite
```
  // Wrap api's addMonitor to allow the calling code to attach
  // additional monitors in the future.  But only in __DEV__ and only
  // if we've attached Reactotron to console (it isn't during unit tests).
  if (__DEV__ && console.tron) {
    apiConfig.addMonitor(console.tron.apisauce)
  }
```

and one that I created:

```
  apiMonitor: (response) => {
    const { duration, problem, status, headers, config, data } = response
    const methodName = config.method ? config.method.toUpperCase() : ''
    const error = new Error(`HTTP Error ${status} - ${methodName} ${config.url}`)

    if (STATUS_CODE_TO_NOT_CATCH.includes(status)) {
      return null
    }

    console.tron.log(`Bugsnag.notify: ${error}`)
    client.notify(error, (report) => {
      report.metadata = {
        request: {
          method: methodName,
          url: config.url,
          headers: config.headers,
          data: config.data,
          params: config.params
        },
        response: {
          status,
          headers,
          data,
          problem,
          duration: `${duration}ms`
        }
      }
    })
  }
```

`Is there more than one listener to the REGISTER_DEVICE_REQUEST action?`
=> nope


The current state of my inspection is:
- the double async storage event is due to `REDUX_PERSIST` which is enabled. If I disable it, I only have the event once
- When I remove the following condition from `addResponseTransform`, the response is on success and I've no `UNKNOWN_ERROR` triggered:
```
if (response &&
        response.headers &&
        !response.headers['content-type'].includes(response.config.headers['Accept'])) {
      return null
    }
```
this condition is used to avoid transform if I'm fetching our API v0
I will add a specific header to do a better check

**Comment by skellock** [comment]
So strange.

I wouldn't think that an early exit from a response transform would cause something strange like this.

What does the server side logs look like?  Do you see multiple requests?  Are there redirects happening?

**Comment by jmeiss** [comment]
I tried several times and I confirm it comes from that early return.

On the server side I've the exact same log (single request), with or without the early return. No redirect on the service side. It's a 204 `No Content`.

Found it!

The difference is that when the API return a 204, there's no `content-type` header. Which means that my condition raise (a silent error :( ) an error

Modifying the condition from
```
    if (response &&
        response.headers &&
        !response.headers['content-type'].includes(response.config.headers['Accept'])) {
      return null
    }
```
to
```
    if (response &&
        response.headers &&
        response.headers['content-type'] &&
        !response.headers['content-type'].includes(response.config.headers['Accept'])) {
      return null
    }
```

solved the issue!

Thank you so much for bringing your pair of eyes on that!!

**Comment by skellock** [comment]
Yay!

Unfortunately I don't know too much about `PushNotification`.

Keep in mind, that when you load async storage on startup, it might not be ready immediately.  It's async.  You might need to defer the saga making that call until you know it has arrived.

**Comment by jmeiss** [comment]
Oki, I will search into that direction. Thanks a lot!
