### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'e.response.status')

### ISSUE THREAD

**Issue by efournival** [skellock/apisauce#115]
I'm getting this error when the following method is called:
```JavaScript
const endpoint = (id, data) => {
  var body = new FormData()
  body.append('myData', data)
  return api.post(
    'user/' + id + '/endpoint', 
    body, 
    { headers: { 'Content-Type': 'multipart/form-data'} }
  )
}
```
`data` is a really huge string (around 400 kB). If I replace `body.append('myData', data)` by `body.append('myData', 'foobar')` then it works.
I've tried with and without the additional config (the content type header) but nothing worked.

The stack trace told me the error is located near:
```JavaScript
  _ = function _(e) {
    return "Network Error" === e.message ? NETWORK_ERROR : axios.isCancel(e) ? CANCEL_ERROR : ramda.cond([[ramda.isNil, function () {
      return T(e.response.status);
    }], [ramda.contains(ramda.__, TIMEOUT_ERROR_CODES), ramda.always(TIMEOUT_ERROR)], [ramda.contains(ramda.__, NODEJS_CONNECTION_ERROR_CODES), ramda.always(CONNECTION_ERROR)], [ramda.T, ramda.always(UNKNOWN_ERROR)]])(e.code);
  }
```

**Comment by efournival** [comment]
I found a workaround by doing this:
```JavaScript
const endpoint = (id, data) =>
    api.post('user/' + id + '/endpoint', data, { headers: { 'Content-Type': 'text/plain' } })
```
Then I have to read directly the request content server-side. 
This is a quite weird POST request but it does work at least.

**Comment by skellock** [comment]
Hmm.. I haven't run into this yet.  What happens if you leave the headers off the original request?  I think this is something does for us.

**Comment by efournival** [comment]
Sorry for the long answer time.
Just checked today and it seems to work... but we did a lot of changes to the code. Maybe I messed up with the `data` object at first (non-resolved promise?) and it leaded to a strange error from apisauce.

**Comment by skellock** [comment]
Roger that.  Swing by again if this reappears.

**Comment by estevanpedro** [comment]
I was having this problem, i had to decrease the attachment image's size.
