### ISSUE TITLE
Integrating redux/saga with api response/request transforms?

### ISSUE THREAD

**Issue by tmaly1980** [skellock/apisauce#116]
I'd be curious if there's an easy way to create global request/response transforms that can either pull content from redux (ie custom headers) or interact with the app after a weird response, such as an expired JWT token? 

Example: if the server says the JWT token is invalid, my RN app needs to automatically redirect to the login screen. I could have a few dozen API endpoints, so the less code I have to add, the better.

Right now the best solution I can think of is to wrap my api call with a handler that can check the status code for authentication failures, and reroute accordingly.

**Comment by skellock** [comment]
Have a look at the async response transforms.  You'll be able to catch JWT expiries, then kick off a renewal, then retry the original request, then swap out the original response for the new retried one.

**Comment by tmaly1980** [comment]
@skellock, can that integrate with redux/sagas at all? Or is it self-contained? I'm familiar with the response transforms, but it doesn't look like I have any context other than the actual response itself. 

Also, retrying won't handle the case where the JWT token is entirely invalid. Is there a way to handle specifically invalid tokens within the response transform, or am I confined to altering the response data structure and leave it up to my saga action to handle the bad token? In my case, there could be a distinction between a "bad token" failure and some other API failure. I was hoping there was some way the transform could connect with the rest of the system (ie redux), but I guess not. 

What I ended up doing was adding a new case that altered my login reducer and wrapped my entire app with a higher order component that will toggle a login screen if authentication is required, the JWT token expires, etc. Not sure how else to handle that without a ton of other code.

**Comment by skellock** [comment]
It sounds like you're trying to trap the workflow synchronously within any saga that talks to the API.  Is that right?

If so, maybe something like this:

```js
// callApiSaga.js

export function * callApi (apiCall) {
  const response = yield apiCall
  if (!isBadToken(response)) {
    return response
  }
  // this triggers your UI to show a login form
  yield put({ type: 'RELOGIN' })
  const action = yield take(['RELOGIN_OK', 'RELOGIN_ABORT'])

  if (action.type === 'RELOGIN_ABORT') {
    return response
  }

  const responseTakeTwo = yield apiCall
  return response
}
```

Then whenever you usually call your API in a saga, call that:

```js
// notice there's no yield here anymore?
const apiCall = call(api.deleteThing, 42)

// that's cuz we're passing it in here:
const response = yield call(callApi, apiCall)
```

So, that's simplified a bit, but ya, that's the gist.

Could something like that work?

**Comment by tmaly1980** [comment]
Thanks @skellock , that's really helpful. I'm new to RN and sagas in general so some of it is a bit over my head. At the very least, I'd want to call my LoginActions to inform my top level container (a HOC Provider) that authentication has failed, so it can toggle my LoginScreen.

**Comment by karlingen** [comment]
@skellock is this still supposed to be working? 

I've tried this: 
```
import { callApi } from './CallApiSaga'
const apiCall = callApi(api.getLocations)
const response = yield call(callApi, apiCall)
```

but the response always returns `undefined`

**Comment by tmaly1980** [comment]
@karlingen, your last two lines should be:

```
const apiCall = call(api.getLocations) // creates the action with call(), not callApi()
const response = yield call(callApi, apiCall) // calls yield inside, on apiCall
```

Personally, I have a custom version of callApi that accepts the api (http client) instance as well, so I can modify headers (add tokens, etc), get a refreshed token automatically, etc.

**Comment by karlingen** [comment]
@tmaly1980 oh whew, I've been trying to fix this for hours now. 😓  Thanks!!

**Comment by tmaly1980** [comment]
LOL. I'd say about 20% of my time with RN is spent on frustrating little tidbits like this.

**Comment by skellock** [comment]
20%?  Man, someday I'll be as efficient as you.  😆

**Comment by ckeeney** [comment]
from https://github.com/infinitered/apisauce/issues/116#issuecomment-316218241 by @skellock 
> Have a look at the async response transforms. You'll be able to catch JWT expiries, then kick off a renewal, then retry the original request, then swap out the original response for the new retried one.

Can you clarify this?  The readme doesn't mention async response transforms, only async request transforms, request transforms, and response transforms.

The [section on response transforms](https://github.com/infinitered/apisauce#response-transforms) says
> Data is the only option changeable.
and gives the following example:

```js
api.addResponseTransform(response => {
  const badluck = Math.floor(Math.random() * 10) === 0
  if (badluck) {
    // just mutate the data to what you want.
    response.data.doorsOpen = false
    response.data.message = 'I cannot let you do that.'
  }
})
```

Suppose I have an expired access token and a valid refresh token and I make a request `/api/me` with the expired access token.  The api will respond with an HTTP response code 401 and some response about invalid tokens.  I can add a response transform using `addResponseTransform` to catch this response, refresh my tokens and re-issue the original request.  I can then swap out the invalid token response data with my actual data. 

What about the headers and response code? `response.ok` is still going to be false in this case.

Am I missing something?
