### ISSUE TITLE
addRequestTransform + addAsyncRequestTransform fail to fire immediately after browser refresh.

### ISSUE THREAD

**Issue by juddey** [skellock/apisauce#123]
I'm using apisauce in a web-based project and am noticing some unexpected behaviour in the api call _immediately after_ a browser refresh. It seems that  `addRequestTransform` or `addAsyncRequestTransform` do not stick in that scenario. Using `0.14.1`.

Code below - It should look remarkably familiar. :smile: 

```
const create = () => {
  // ------
  // STEP 1
  // ------
  //
  // Create and configure an apisauce-based api object.
  //
  const api = apisauce.create({
    // base URL is read from the "constructor"
    baseURL,
    // here are some default headers
    headers: {
      accept: 'application/vnd.api+json',
      'content-type': 'application/vnd.api+json'
    },
    // 10 second timeout...
    timeout: 10000
  })

  api.addAsyncRequestTransform(request => async () => {
    api.setHeader('awesome-async-dude', 'Steve Kellock')
  })

  api.addRequestTransform(request => {
    api.setHeader('awesome-sync-dude', 'Gant Laborde')
  })

```
I'm looking on my back end and I can see that the headers are not set in the request immediately following the browser refresh, but from the next request onwards, they are present (both `awesome-async-dude` and `awesome-sync-dude`).

Strangely enough, If I `console.log` out the activity I see that both the methods are called during processing of all requests, but I am unsure of the order that they actually resolve (thanks, sync processing).

Is this weird, or have I missed something somewhere along the line?

PS. I've simplified the headers I am setting with the transform  in an attempt to isolate the problem - I removed an async call to get an auth token, which makes far more sense!

**Comment by skellock** [comment]
Hey @juddey !

So this because the headers are locked in at the [start of the call](https://github.com/skellock/apisauce/blob/master/lib/apisauce.ts#L206), and then the transforms happen after that.

To change the request headers for that particular request, you can modify the `.headers` object of the request in your transform.

Not ideal, I know.

**Comment by juddey** [comment]
Hey Steve,

Thanks for the explanation - although I am not sure why that order affects things, but that is just a shortcoming in my understanding. I've added some logic to my startup saga which retrieves the key from localstorage and adds it to the api (if the key is present) and that seems to have fixed the problem.

I'll close this out now, thanks for the help. :+1:

**Comment by juddey** [comment]
So @skellock I have been having more fun + games with this today. 

This problem seems to be occurring on the first api call that is made that requires the token to be added. Once one call fires the token gets set, and then things roll along just peachy. 

My problem is that the first api call could potentially be to _any_ api endpoint. I'm not sure what the best way to cater for this scenario is: I could include a check on each saga function to set the token, but checking in each saga file seems too far down the food chain.

Any ideas on where this could be set? Appreciate the thoughts :smile:

**Comment by skellock** [comment]
```js
api.addAsyncRequestTransform(request => async () => {
    api.setHeader('awesome-async-dude', 'Steve Kellock')
     request.headers[‘awesome-async-dude’] = ‘Steve Kellock’ // change the current request too
  })
```

Does something like that work?

**Comment by skellock** [comment]
Ugh, butchered the format because iPad.

**Comment by juddey** [comment]
Ah! Yes, thanks Steve, that worked a treat. Didn't realise that I could also morph the current request in that transform, which now makes your earlier comment make perfect sense. Thanks for clarifying for me.

**Comment by skellock** [comment]
Ya, it's an awkward interface.  Sorry for the confusion.
