### ISSUE TITLE
Is it possible to abort a request?

### ISSUE THREAD

**Issue by deoqc** [skellock/apisauce#13]
Title says it all.

**Comment by skellock** [comment]
As far as I know, the answer is no.

Here's some background on it. 

https://github.com/mzabriskie/axios/issues/50

People seem to be trying come up with the best approach for cancelling promises.

**Comment by deoqc** [comment]
Thanks @skellock, didn't know about this problem.

**Comment by messense** [comment]
https://github.com/mzabriskie/axios/pull/452

Request cancellation has landed in axios.
