### ISSUE TITLE
Document how to run tests

### ISSUE THREAD

**Issue by gabceb** [skellock/apisauce#14]
I tried running `npm test` using Node 6/NPM 3.8.9 and Node 4/ NPM 2.15.1 with no luck. Both complained about the `import` statements so I guess they were not being transpiled by babel.

When running Node 4 I also had to install `babel-core` and `babel-plugin-transform-runtime` because these were not part of the deps of the project.

**Comment by skellock** [comment]
You're right.  Thanks for the bug report.

**Comment by gabceb** [comment]
Kudos for the fast response 🙌🏻

**Comment by skellock** [comment]
Just released 0.1.4.  Thanks again.
