### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by GantMan** [skellock/apisauce#16]
Supposedly awaiting features in 0.25, I know you were planning on doing timout in constructor.

It appears they've added an onTimeout.   Would be a good add-on to assure this works with API sauce and associated docs.

**Comment by skellock** [comment]
agreed.  ill follow up on #7

**Comment by GantMan** [comment]
woops, didn't put together this was tied in #7

**Comment by skellock** [comment]
Good news.

![image](https://cloud.githubusercontent.com/assets/68273/16528180/230d2d6a-3f89-11e6-85b8-7d250127dbea.png)

Timeouts are now being reported correctly.
