### ISSUE TITLE
Function that returns a promise, to return response.

### ISSUE THREAD

**Issue by GantMan** [skellock/apisauce#17]
I'm not terribly sure if I'm missing something basic.  This could just be my ignorance.

I want to do something special when `login` api is called.   It should do something with response, then return the promise.   But it appears to swallow `response`

Ergo:
```javascript

api
  .post('/repos/skellock/apisauce/commits')
  .then((response) => response.data[0].commit.message)
  .then((response) => window.alert(response.data.taco))
```

second promise is like "WUT?  WUTs this response thing yo?"

This is critical, because I want a certain API function to update headers, but not to keep response away from the following paths the promise might be handed.   I hope I made this clear... I need coffee ☕

**Comment by skellock** [comment]
When you chain promises like this, the output of one becomes the input of the next.

If you want your 2nd then to accept the response, you'll need to return it from the first, instead of message.

**Comment by GantMan** [comment]
AH!  DUH!  I still suck at keeping my promises.
