### ISSUE TITLE
Request body broken

### ISSUE THREAD

**Issue by redspear** [skellock/apisauce#21]
Not sure if I'm missing something simple or not. 
When I send a POST request that has two or more parameters the request is rejected.

The request body for a successful request usually looks like this:
`{ email: 'w@k.co', password: 'xxxxxx' }`

but instead I get this:
`{ '{"email":"w@k.co","password":"xxxxxx"}': '' }`

If I have only one parameter it works fine.
Using in a react native app made with the infinitered/ignite generator.

**Comment by skellock** [comment]
It looks like it's arriving as a key.  That's super strange.

Are you able to share the line of code that's making the request with me?

**Comment by redspear** [comment]
From Api.js in the Ignite app:
`const userLogin = (emailAdr, pwd) => api.post('/user/user_login', {email: emailAdr, password: pwd})`

`    headers: {
      'Cache-Control': 'no-cache',
      'Content-Type': 'application/x-www-form-urlencoded'
    },`

From the APITestingScreen.js file:
`const endpoints = [
  { label: 'User Login', endpoint: 'userLogin', args: ['w@k.co', 'xxxxxx'] }
]`

**Comment by skellock** [comment]
Ah.  Ok.

You're using `x-www-form-urlencoded` as a `Content-Type` header.

`apisauce` uses `axios` as the library to make the request.  It has this feature where it "stringifies" your data when it sees that header.

The reason why is that format is expecting a string and not a JSON object.

So, you have a couple of options.

1. You can convert your JSON object into form encoded format.
2. Remove that header and see if the server supports accepting `application/json`
3. If not supported, change the server to support that format (if it's Rails, it's easy).

**Comment by redspear** [comment]
Removed the Content-Type header and it worked straight away.
Thanks for your help!
