### ISSUE TITLE
weird "NETWORK_ERROR" while connect to my server

### ISSUE THREAD

**Issue by ksaynice** [skellock/apisauce#22]
I was following the infiniteRed/ignite way to making api calls by using redux / redux-saga

but I got wired "NETWORK_ERROR" when I was trying to make api call to my sever on AWS even on localhost.
but under the same network condition, I replaced the baseURL to the github demo one, which works just fine (returning some 'CLIENT_ERROR' since I was calling the non-exist endpoint)

this is what I logged response:
Object {duration: 246, problem: "NETWORK_ERROR", ok: false, status: null, headers: null…}
config
:
null
data
:
null
duration
:
246
headers
:
null
ok
:
false
problem
:
"NETWORK_ERROR"
status
:
null

does someone have any insight about this? and I noticed that '[NEW] Network errors and timeouts are now detected on React Native - @skellock' on 0.2.0 release, then I upgrade apisuace to 0.3.0, but the error happens  - -

**Comment by skellock** [comment]
Hmm... wrong server name or port?  Can you verify you can connect via something like Postman?

**Comment by ksaynice** [comment]
yep, I verified them by postman / Chrome, I assume the default port is 80?

**Comment by skellock** [comment]
Strange.  Yep.  Default is port 80 for http.  443 for https if you're connecting like that.

Are you running on iOS 9+?

If so, can you check your info.plist for the http exception if you're using http?

https://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/

**Comment by ksaynice** [comment]
pretty strange, ok let me check that, also is there a way that I can log the request, since it could also be my redux persist  thing

**Comment by skellock** [comment]
Ya, you could always `console.log(response)` to see what's going on.  Perhaps axios might have more information.   If you haven't set your transport security exception and you're using iOS 9 + http, then it's pretty much that.

It'd be nice if the network error that came back was a little more descriptive.  Depending on the device, sometimes it just says, "Error".  Hehe.

**Comment by ksaynice** [comment]
thanks for the advise and quick respond @skellock I had setup Per-Domain Exceptions in the info.plist and it works :)
btw actually the log on my first comment was the one from console.log(response) which has no request info, thats why I wonder could be my redux presist thing so I wish that we can also log the request. anyway thanks for the help and good Sauce for apis

**Comment by baskan** [comment]
for info, this saves a lot of time :  http://www.preslav.me/2017/03/26/debugging-network-calls-in-react-native-using-the-chrome-debugger/

in my case, this was a cors header error

**Comment by hammadzz** [comment]
Having the same issue with https and must be something on my AWS API Gateway but it doesn't help to debug when the error is misleading. I have no idea what the actual error is. Don't know if it is axios or apisauce holding back info.

All I get in response is data null, headers null, status null, problem NETWORK_ERORR

**Comment by cretumarius** [comment]
> curl -v

I suspect that is my issue too. How can I fix this?

**Comment by uxinnuendo** [comment]
Came here for an answer and didnt find one, so here was my issue incase it helps anyone:
The internals don't seem to properly handle incorrect payloads - in my case, I was accidentally including a Date object in the payload, and the raw dump of the internal Axios error doesnt give anything away:

`AxiosError: Network Error
    at handleError (192.168.1.105:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:154868:39)
    at call (native)
    at dispatchEvent (192.168.1.105:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:42636:31)
    at setReadyState (192.168.1.105:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:40459:33)
    at __didCompleteResponse (192.168.1.105:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:40245:29)
    at apply (native)
    at anonymous (192.168.1.105:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:40387:52)
    at apply (native)
    at emit (192.168.1.105:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3063:40)
    at apply (native)
    at __callFunction (192.168.1.105:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3684:36)
    at anonymous (192.168.1.105:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3404:31)
    at __guard (192.168.1.105:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3621:15)
    at callFunctionReturnFlushedQueue (192.168.1.105:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3403:21)`

**Comment by Philip970** [comment]
Hello I have an error 403 on iOS only that is on the emulator or the phone. on android it works fine. I need help.

apisauce : 3.0.1
expo : 19.0.11
RN : 0.72.6

here is the return object : 

{"config": {"adapter": ["xhr", "http"], "baseURL": "http://3.137.55.229:8015/api", "data": undefined, "env": {"Blob": [Function Blob], "FormData": [Function FormData]}, "headers": [Object], "maxBodyLength": -1, "maxContentLength": -1, "method": "get", "params": {}, "timeout": 10000, "transformRequest": [[Function transformRequest]], "transformResponse": [[Function transformResponse]], "transitional": {"clarifyTimeoutError": false, "forcedJSONParsing": true, "silentJSONParsing": true}, "url": "/posts?page=1&page_size=10&search=", "validateStatus": [Function validateStatus], "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN"}, "data": {"detail": "Informations d'authentification non fournies."}, "duration": 699, "headers": {"allow": "GET, POST, HEAD, OPTIONS", "content-language": "fr", "content-length": "58", "content-type": "application/json", "cross-origin-opener-policy": "same-origin", "date": "Tue, 26 Dec 2023 15:37:45 GMT", "referrer-policy": "same-origin", "server": "Microsoft-IIS/10.0", "vary": "Accept, Accept-Language, Cookie, Origin", "x-content-type-options": "nosniff", "x-frame-options": "DENY", "x-powered-by": "ASP.NET"}, "ok": false, "originalError": [AxiosError: Request failed with status code 403], "problem": "CLIENT_ERROR", "status": 403}
