### ISSUE TITLE
Middleware feature

### ISSUE THREAD

**Issue by maluramichael** [skellock/apisauce#23]
Is it possible to implement a middleware feature like the addMonitor method? Like if i want to handle every response in a certain way. Now i have to add to every request a .then

**Comment by skellock** [comment]
That's what addMonitor does, but I think I might not reading you right.

Are you looking for an opportunity to change the response somehow before it gets to your normal path of execution?

**Comment by maluramichael** [comment]
Yeah thats what i want to do. I have an api which sends some useless data so i want to clean all responses.

**Comment by maluramichael** [comment]
Now i do this for all of my api requests:
```javascript
all() {
	return this.api.get('/business_stores').then(CleanupResponse);
}
```
But it would be nice if i could do something it like this:
```javascript
this.api.addMiddleware(response=>{
	return CleanupResponse(response);
});
```
This middleware would be called right after the response is received from the server and passed to the first then.

**Comment by skellock** [comment]
Ok, new version is out.  It has this feature now:

https://github.com/skellock/apisauce#adding-transforms

Thx.

**Comment by maluramichael** [comment]
Wow that was fast. Thank you so much.

**Comment by BigPun86** [comment]
Great work @skellock
