### ISSUE TITLE
add transform to GET

### ISSUE THREAD

**Issue by GantMan** [skellock/apisauce#27]
Docs clearly say PUT/POST/PATCH gets `addRequestTransform` but I could sure use it for a GET.  Any reason it's not supported?

If philosophically, then let's discuss.

If just not done yet, then I'd love to add it!

**Comment by skellock** [comment]
The only mutable part of `addRequestTransform` is the data.   Data isn't passed unless its PUT/POST/PATCH.

I have a feeling you're after modifying the headers.  Or maybe appending QSVs?

I'm sure we can make it work, lemme know your use case!  🎉

**Comment by GantMan** [comment]
appending a QSV, you are correct.   But I could very likely be modifying headers for any client that demands a login token.

**Comment by skellock** [comment]
Ok @GantMan `0.5.0` has just been released with mutable everything for `addRequestTransform` (see #28 for the specifics).

For example:

```js
api.addRequestTransform(request => {
  request.headers = { 'X-Kanye': 'Imma let u finish but...' } 
  request.params['page'] = 42
  delete request.params.secure
  request.url = request.url.replace(/\/v1\//, '/v2/')
})
```

I feel like I just handed you a loaded gun.  

Good luck!

**Comment by GantMan** [comment]
## I should be ok with a loaded gun
![image](https://cloud.githubusercontent.com/assets/997157/18036937/8b375aa0-6d3d-11e6-9df8-e26ff52b3d6d.png)
