### ISSUE TITLE
Send body as string

### ISSUE THREAD

**Issue by maluramichael** [skellock/apisauce#29]
We got some weird api which requires the body of the POST request to be a string like this
`username=xyz&password=abc`
And the content type has to be 

I tried the following
```javascript
const body = {username, password};
// and 
const body = `username=xyz&password=abc`;
const options = {
	headers: {
		'Accept'      : 'application/json',
		'Content-Type': 'application/x-www-form-urlencoded'
	}
};
return this.api.post('/tokenAuthentication/getToken.json', body, options);
```

In both cases it didn't worked. How do i send a request with just a string?

**Comment by maluramichael** [comment]
Oh damnit. I think it is working just with the string. My bad i did something wrong somewhere else.

**Comment by skellock** [comment]
Sweet.  Lemme know if it is something with apisauce.  I think I've experienced something like this before.
