### ISSUE TITLE
Undefined only on android

### ISSUE THREAD

**Issue by maluramichael** [skellock/apisauce#32]
When i try to fetch anything from my api i get the following error in pidcat: `[TypeError: undefined is not an object (evaluating 'error.response.status')]`. In your source is only one place with `error.response.status`

``` javascript
var getProblemFromError = function getProblemFromError(error) {
    // first check if the error message is Network Error (set by axios at 0.12) on platforms other than NodeJS.
    if (error.message === 'Network Error') return NETWORK_ERROR;
    // then check the specific error code
    return R.cond([
    // if we don't have an error code, we have a response status
    [R.isNil, function () {
      return getProblemFromStatus(error.response.status);
    }], [R.contains(R.__, TIMEOUT_ERROR_CODES), R.always(TIMEOUT_ERROR)], [R.contains(R.__, NODEJS_CONNECTION_ERROR_CODES), R.always(CONNECTION_ERROR)], [R.T, R.always(UNKNOWN_ERROR)]])(error.code);
  };
```

Do you know what my problem is and what i'am doing wrong?

I use this commit https://github.com/skellock/apisauce/commit/7aa56ac3520e19a8327d8038af8ec8fb0079ffb5 and rn 0.32.0

**Comment by skellock** [comment]
Axios changed their interface in their latest version and it looks like my logic missed a scenario.

https://github.com/skellock/apisauce/blob/master/lib/apisauce.js#L149

Are you on a device?   Is that device set to a non english setting?  Which android version are you using?

Thanks for taking the time to report this.

**Comment by maluramichael** [comment]
Thanks for your fast response @skellock. I'am on a real device 'Sony Xperia Z3 6.0' and it is set to german.

**Comment by skellock** [comment]
I bet https://github.com/skellock/apisauce/blob/master/lib/apisauce.js#L173 is the problem.  We're looking for an english match.

I did it like this because at the time, React Native wasn't bubbling up the right platform networking error.   There have been several changes since then, so I'll have to go back and revisit that error message.

**Comment by maluramichael** [comment]
When i type the following in my terminal `adb shell input keyevent 82` the debug menu on my device opens and i press `Debug JS Remotely` everything works fine. When i disable the remote debugger every call throws the Network error.

**Comment by maluramichael** [comment]
Well i think i found MY error. I done something wrong in one of my transformers and it crashed. It looked like this

```
          ReactNativeJS  I  Running application "Lago" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
                         I  { [TypeError: undefined is not a function (evaluating 'objectToClean.id.lastIndexOf('/')')]
                         I    line: 122328,
                         I    column: 56,
                         I    sourceURL: 'http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false' }
                         I  { [TypeError: undefined is not an object (evaluating 'error.response.status')]
                         I    line: 121005,
                         I    column: 43,
                         I    sourceURL: 'http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false' }
```

**Comment by skellock** [comment]
Feel free to reopen if this is still causing grief.  Thanks!
