### ISSUE TITLE
use request transformers to abort request if condition unmet

### ISSUE THREAD

**Issue by alzalabany** [skellock/apisauce#34]
it would be nice if we can setup a transformer that can intercept a request and delay its execution until some condition is met.

in my case i'm using api-sauce in an react-native app. i want to intercept any api call IF user is not online and either cancel it. or delay its execution;

i tried returning rejected promise in requestTransformer but it doesnot work

```
const api = apisauce.create({
  baseURL,
  headers: header,
  timeout: 20000,
});
api.addRequestTransform((request) => {
  if(!Config.isOnline()) {
    return new Promise((ok, not)=>not({ok: false, data: {message: 'Your device is not connected to internet'}, status: 412}));
  } else {
    return request;
  }
});
```

is there another method to reject request before sending it if some condition is unmet ?
it would be very nice also if we can keep the request pending until device is back on the resolve promise :).

thanks

**Comment by skellock** [comment]
This is in place now.
