### ISSUE TITLE
Is it possible to change the baseURL after the api is created?

### ISSUE THREAD

**Issue by maluramichael** [skellock/apisauce#36]
Something like this:

```javascript
this.api = create({
  baseURL:'localhost:8999'
})

this.api.setBaseURL('somefancyapi.com');
```

**Comment by skellock** [comment]
Axios allows you, but we should definitely have a way.  In fact, exactly like you suggest.  👍

**Comment by messense** [comment]
+1 for this.

**Comment by ippily** [comment]
I'm trying to transform my baseURL by replacing the subdomain like so: 
`const create = (baseURL = 'https://\/subdomain\/.mywebsite.com/api') => {
api.addResponseTransform(response => {
response.baseURL = response.config.baseURL.replace(/\/subdomain\//, 'mySubdomain')
})
}`

I keep getting a problem of status NETWORK_ERROR, don't know why it's not working out? the response transform manages to change the URL but at the end the API response comes out incorrectly.

**Comment by skellock** [comment]
If you console.log what the replacement turns out to be, is it what you expect?

**Comment by ippily** [comment]
So I am able to transform the response to the correct replacement, however I the result is a null GET with Status Code ¯\_(ツ)_/¯

Any ideas?

**Comment by ippily** [comment]
when api.addResponseTransform is called, is the url changed before or after the request is made?

**Comment by skellock** [comment]
After.

`addRequestTransform` is the before part.  Although, since you're kicking off the call yourself, you can change the parameters to be whatever you like.

**Comment by ippily** [comment]
The thing is I don't want to change anything in the the request which in my case would be `api/v1/myAPIcall`
I would like to change 'subdomain' in the following URL:
`https://subdomain.mywebsite.com/api/v1/myAPIcall`

**Comment by skellock** [comment]
To change it, you've got a few options.

* You can just create a brand new `api` object with the baseURL being what you want.
* You can call `api.axiosInstance.setBaseURI('xxx')` to change the instance (this is the thing I'll make easier to do that was suggested at the start of this ticket).
* You can do it per request: `api.getThing('myApiCall', {x: 1}, { baseURI: 'swappyswap.com' })`.

It sounds like your situation is you connect to an API, then part way through the "session", you change the API's sub-domain.  

I'd do bullet point 1, personally, unless you've got a bunch of "state" packed into the API object.

**Comment by skellock** [comment]
This is now in the library.  Thanks all!

**Comment by Dictory** [comment]
Sorry for my question, but i don\`t have idea how change url. I pass my api (after api = Api.create()) to my Saga and wont change base url inside saga:
```javascript
api.setBaseURL(apiUrl);
```
but get error: `api.setBaseUrl is not a function`, api contains only functions for request, doesn\`t have `setBaseUrl`.
Thanks.

**Comment by maluramichael** [comment]
@Dictory https://github.com/skellock/apisauce#changing-base-url try api.setBaseURL instead of api.setBaseUrl

**Comment by Dictory** [comment]
@maluramichael Wow so fast answer, thanks. I already know, i just add setBaseURL to exports xD

**Comment by markrickert** [comment]
From @skellock's reply above:

> You can do it per request: api.getThing('myApiCall', {x: 1}, { baseURI: 'swappyswap.com' }).

There's a typo and it should be `baseURL` when setting a URL for a specific API call.
