### ISSUE TITLE
Uploading files with apisauce

### ISSUE THREAD

**Issue by nuhbye** [skellock/apisauce#37]
I don't seem to find a way to upload files with apisauce.

Thanks
Kunal

**Comment by skellock** [comment]
Hello.  Have a look at the `axios` docs.  It really depends on your API, however, most likely you'll end up filling in a FormData object, and posting that up.

Lemme know if you get stuck.

**Comment by matart15** [comment]
How can i Upload file with react native.
I am using ignite. https://github.com/infinitered/ignite
whitch uses apisauce by default.

normal post request works on android.
but file upload does not.

```
const uploadPost = (videoUrl) => {
    var video = {
      uri:  videoUrl,
      type: 'image/jpeg',
      name: 'photo.jpg',
    };

    var body = new FormData();
    body.append('authToken', 'secret');
    body.append('post_video', video);
    body.append('title', 'A beautiful photo!');

    let url = 'post?api_version=1'
    return api.post(url, body)
  }
```

It gives me NETWORK_ERROR on android. Sends request on ios

**Comment by tmaly1980** [comment]
@skellock Unfortunately, I am having ZERO luck figuring this out. I've looked through axios' documentation and tried several approaches, none of which have worked. Most of the examples out there use fetch(). I'm trying to get it working with react-native-image-picker.

**Comment by skellock** [comment]
```js
const uploadImage = (pathToImageOnFilesystem) => {
    const form = new FormData()
    form.append('image[image]', {
      name: 'omgitsme.jpg',
      uri: pathToImageOnFilesystem,
      type: 'image/jpg'
    })
    const headers = {
      'Content-Type': 'multipart/form-data'
    }
    return api.post('/endpoint/to/upload', form, { headers })
  }
```

Try something like this.

**Comment by PiggyDev** [comment]
I am using apisauce for all my api calls but for uploading images, I ended up using https://github.com/kamilkp/react-native-file-transfer. This kind of is not a good solution, I would have loved to do all through the single way.
Will try to do it the way suggested above by @skellock

**Comment by nuhbye** [comment]
I am using apisauce for all my api calls but for uploading images, I ended up using https://github.com/kamilkp/react-native-file-transfer. This kind of is not a good solution, I would have loved to do all through the single way.
Will try to do it the way suggested above by skellock

**Comment by tmaly1980** [comment]
@skellock OK good to know. Seems my issue is actually caused from https://github.com/jhen0409/react-native-debugger/issues/38
