### ISSUE TITLE
response with status 400 resolved successfully instead of rejected

### ISSUE THREAD

**Issue by sckoh** [skellock/apisauce#38]
"apisauce": "0.6.0"

    api.post('/oauth/token', data)
       .then((res) => console.log(res));

the below response is logged in "then"

    {
        "duration":190,
        "problem":"CLIENT_ERROR",
        "ok":false,
        "status":400,
        "headers":{
            "content-type":"application/json;charset=UTF-8",
            "access-control-allow-origin":"",
            "pragma":"no-cache, no-cache",
            "x-xss-protection":"1; mode=block",
            "transfer-encoding":"Identity",
            "access-control-max-age":"3600",
            "expires":"0",
            "cache-control":"no-cache, no-store, max-age=0, must-revalidate, no-store",
            "date":"Mon, 23 Jan 2017 23:37:54 GMT",
            "access-control-allow-credentials":"true",
            "x-content-type-options":"nosniff",
            "vary":"Accept-Encoding",
            "x-frame-options":"DENY"
        },
        "config":{
            "transformRequest":{

            },
            "transformResponse":{

            },
            "headers":{
                "Accept":"application/json",
                "Content-Type":"application/json",
            },
            "timeout":0,
            "xsrfCookieName":"XSRF-TOKEN",
            "xsrfHeaderName":"X-XSRF-TOKEN",
            "maxContentLength":-1,
            "baseURL":"http://114.119.116.135:8000/fe-oauth",
            "method":"post",
            "url":"http://localhost:8000/oauth/token",
            "data":"{\"grant_type\":\"password\"}"
        },
        "data":{
            "error":"invalid_request",
            "error_description":"Missing grant type"
        }
    }

**Comment by skellock** [comment]
Indeed it does!  There are two properties to check results.  `ok` if it was 200 series, and `problem` will have a constant with a better description. `status` is a third way if your app cares about specific codes.
