### ISSUE TITLE
Exception '-[__NSCFNumber length]: unrecognized selector sent to instance 0xb0000000000011a5' was thrown while invoking sendRequest on target RCTNetworking with params

### ISSUE THREAD

**Issue by Chronaly** [skellock/apisauce#39]
Hi, I'm seeing the following error when I make a request to my apisauce API, which is structured as a singleton. Any idea why this is occurring? It's happening on my 4th API call.

**Comment by skellock** [comment]
Hmm.  What does the code look like?

Looks like there might be an object in a spot where a string might be expected.
