### ISSUE TITLE
Response transformers don't change the data

### ISSUE THREAD

**Issue by maluramichael** [skellock/apisauce#45]
I cannot change the data anymore within a response transformer.

```
api.addResponseTransform((response)=> {  
  response.data = { ... }
});

api.get('user').then(response=>{
  console.log(response.data); // the original data from my api
})
```

Is it possible that the transformer api has changed?

EDIT: ok my cleanup function has changed. Before i have done something like this
```
API.request.addResponseTransform((response)=> {
    if ( response.ok ) {
        HydraCleanUp(response.data);
    }
});
```
HydraCleanUp mutated the data inside the response.data object;

Now i have this code

```
API.request.addResponseTransform((response)=> {
    if ( response.ok ) {
        const data = HydraCleanUp(response.data);
       response.data = data;
    }
});
```

And this does not work because i would assign another reference to response.data;

**Comment by skellock** [comment]
Did you see see the buggy behaviour in 0.7.0?  I did change logic with how that worked, but my intention was to *add* and not *modify*.  

https://github.com/skellock/apisauce/pull/44/files

Are you able to pin to 0.6.0 and everything just magically work again?  

If that's the case, then I introduced some problems for sure.

**Comment by skellock** [comment]
Fixed up in the latest.
