### ISSUE TITLE
No Content-Type sent on POST when body is FormData 

### ISSUE THREAD

**Issue by NSulik** [skellock/apisauce#48]
When making a post request with the body being a FormData object, there doesn't seem to be a Content-Type set , nor can I manually set that header. It seems to be overwritten to nothing.

**Comment by skellock** [comment]
Are you able to pass an object to the 3rd parameter?  This gets passed along directly to axios to customize the request config.  You can set the headers in there if you'd like.

Do you have some code I can look at?

**Comment by NSulik** [comment]
I figured out that it was being set, just not displayed in my inspector (Passed it through a proxy later to figure it out).
Basically I thought this was the problem (The server I was posting to gave me a cryptic response of wrong body type), when it was actually a react-native iOS issue (before 0.41.0, their implementation of multi-part for data (They allowed '/' characters which are not allowed).

Sorry about that, I'll close this issue.

**Comment by skellock** [comment]
Np!  Thanks for following up.

**Comment by franzejr** [comment]
I might have something like that:

```javascript
const authedInstance = () => {
  return AsyncStorage.getItem('auth_token').then((authToken) => {
      return create({baseURL: `${BASE_URL}`,
          headers: {
            'Content-Type': 'application/json; version=2',
            'Authorization': `Token token=${authToken}`
          }
      })
    })
}
```

My `Content-Type`is not being sent.
