### ISSUE TITLE
testing and mocking apisauce examples

### ISSUE THREAD

**Issue by radelcom** [skellock/apisauce#50]
Hello

We have recently investigating React Native for cross-platform mobile development and been using this awesome library. I am in the point of investigating unit testing and trying to mock the async of apisauce in my Redux's Actions. 

I followed the recommended approach in Redux Writing Test [documentation here](http://redux.js.org/docs/recipes/WritingTests.html#async-action-creators) with no success. My JS is level is pretty beginner and was wondering if anyone using this library can share what you did for testing/mocking Actions in Redux.

**Comment by skellock** [comment]
Heyo!

I personally do all my mocking at the `redux-saga` level.  It makes it trivial to do that async mocking stuff there.

I don't like to do a lot in my action creators.  Just create actions.

I'll keep this issue open though.  Maybe others have good suggestions?

Also have a look at how people mock axios.  This library is just a thin wrapper around that.

**Comment by radelcom** [comment]
@skellock tx for giving me some hint. For anyone still looking for solution to this. I was able to resolve my problems using [axios-mock-adapter](https://github.com/ctimmerm/axios-mock-adapter) package. Pretty straight forward and got me up to speed right away.

**Comment by jasongaare** [comment]
@radelcom could you explain more how you got that package to work? I'm attempting to use `apisauce` then grab the `axiosInstance` from it, then use that to pass into in my `MockAdapter` but I keep getting responses that look like this:

    { duration: 22,
      problem: 'UNKNOWN_ERROR',
      ok: false,
      status: null,
      headers: null,
      config: null,
      data: null }

Any further insight on how you were able to do this would be helpful. Thanks!

**Comment by skellock** [comment]
If you can put up a sample repo, I'd be happy to take a closer look.  I had a quick look https://github.com/ctimmerm/axios-mock-adapter#example and it looks like it should be compatible.

**Comment by alexmngn** [comment]
@skellock I have tried to use axios-mock-adapter as well but I can't make it to work. Could you provide a sample example?

**Comment by skellock** [comment]
I haven't used it yet.

**Comment by skellock** [comment]
Ok, just tried it.

Here's a sample `jest` test:

```js

import MockAdapter from 'axios-mock-adapter'

test('mock adapter', async () => {
  const api = API.create()
  const mock = new MockAdapter(api.axiosInstance)
  mock.onGet('/rate_limit').reply(201, {
    x: 'hello'
  })
  const response = await api.getRate()
  expect(response.ok).toBe(true)
  expect(response.status).toBe(201)
  expect(response.data).toEqual({ x: 'hello' })
})
```

To make this work, I have my `api` expose the `axiosInstance`.

```js
import apisauce from 'apisauce'

const create = (baseURL = 'https://api.github.com/') => {
  const api = apisauce.create({
    baseURL,
    headers: {
      'Cache-Control': 'no-cache'
    },
    timeout: 10000
  })
  const getRate = () => api.get('rate_limit')

  return {
    getRate,
    axiosInstance: api.axiosInstance
  }
}

// let's return back our create method as the default.
export default {
  create
}

```

**Comment by robinheinze** [comment]
@skellock I just used this example 5 years later 😆
