### ISSUE TITLE
204 response with ok false on Android

### ISSUE THREAD

**Issue by andrejunges** [skellock/apisauce#52]
So, I'm not sure you are gonna be able to reproduce it. But I think its worth I mention this bug.
react native v. 0.33.1
axios v. 0.8.0

In a simple POST, Im getting back a `ok` with False, in a 204 (no content) response.

Now the tricky part:
It only happen on Android in production.
It didn't happen on iOS (prod or dev), neither on Android in development mode (emulator and device).
During the local tests, I was pointing to the production environment.

Any ideia what might cause that?

**Comment by skellock** [comment]
Strange.  Hmm..

Can you see the request hit the server?  Anything in the logs server-side?

Are you able to rule out SSL certificate errors?  Is there any hints in `adb logcat`?

**Comment by andrejunges** [comment]
Yes, the request hit the server.
The POST is responsible for changing the user's password. And even in those situation where I got an ok false, the password is changed successfully.
My current workaround is this
```if (response.ok || response.status === 204)```

I can do further investigations tomorrow regarding the SSL, but on the server logs I got nothing, it just shows that the POST was requested..

**Comment by n2liquid** [comment]
Since the server got the request and even sent a response, it can't be an SSL AFAIK, since certificate problems would prevent the handshake itself from completing.

**Comment by skellock** [comment]
Indeed.  Good point @n2liquid .  

I'm a bit stumped here.  It seems we've got a scooby doo mystery on our hands.

Maybe if we take a look at the changelogs for React Native from 35+, we might see something networking related?

**Comment by aemdy** [comment]
+1 I'm experiencing the same issue on Android production!

**Comment by skellock** [comment]
Do you have some details @aemdy to help track this down?

**Comment by aemdy** [comment]
This problem wasn't very critical in my situation, so I didn't spend much time trying to understand what causes the problem. In my case it was a user logout view, so I actually didn't care too much if request succeeded or not.

It was reproducible only on Android (both debug and production modes). On iOS everything is fine.

- Executed POST to /auth/revoke-token with some form data.
- Request reached the server and it responded with status 204 (no content)
- response.ok was false, response.status was null, I could identify it as NETWORK_ERROR, nothing else.

Hope this helps.

**Comment by skellock** [comment]
Thx for the info!

**Comment by SerhiiRubel** [comment]
+1 I've the same problem as @aemdy.
It was reproducible only on Android (both debug and production modes). On iOS everything is fine.

React native 0.61.4
apisauce 1.1.1
Executed DELETE request.
Request reached the server and it responded with status 204 (no content)
response.ok was false, response.status was null, I could identify it as NETWORK_ERROR, nothing else.
