### ISSUE TITLE
Post request gives "GET" as response.data

### ISSUE THREAD

**Issue by novotnej** [skellock/apisauce#53]
Hi, I've been struggling with this for a while and can't seem to find a solution. 

I am sending this request:
```javascript
//Service
const postPasswordLogin = function (email, password, deviceId, deviceType) {
    var data = {email, password, deviceId, deviceType};
    return api.post('/sign-in/password', data);
  };
//Saga
const response = yield call(api.postPasswordLogin, email, password, 'alibaba', 'android');
console.log(response);
```
but I keep getting a response like this:
```
Object
config:Object
data:"GET"
duration:1177
headers:Object
ok:true
problem:null
status:200
```

if I test the API request with postman using the same JSON object as I see in config and with application/json headers, server responds just fine. With apisause it seems like it's attempting to send some kind of error (because response header is text/html instead of JSON), but such error won't have a 200 status code and definitely will have some response.. 

any ideas?

**Comment by skellock** [comment]
Hmm... I mean, your code looks totally normal.  You might be able to log with `console.dir(response)`.

The `data: "GET"` seems a bit strange to me though.  Unless that's what you're returning back from the server.  

That `config` object will contain the headers that were sent to the server for your request.  Have a look inside there.

Also, do you have any request or response transforms?  Are you setting a header when you create the `api` object?

**Comment by novotnej** [comment]
yeah I know, that's what strikes me as odd as well, but there is no way the server returned that. The only possilbe outcomes are

- code 200, content-type: application/json; charset=utf-8 
- code 500, some html message
- code 404 with HTML error

in the config object the headers are
Accept:"application/json"
Content-Type:"application/json"

and I commented out all response transforms when I started suspecting something might be wrong there...

**Comment by skellock** [comment]
If you're using React Native, what version are you using?  and what simulator os version?  Version 0.8 of apisauce?

**Comment by novotnej** [comment]
hmm, no, strangely ignite generated it with:
"react-native": "0.38.0",
"apisauce": "^0.6.0",

I'll try to upgrade the version and get back to you on this

**Comment by skellock** [comment]
Upgrading an existing project passed 0.40.0 is a bit of a bear.  Check out https://twitter.com/skellock/status/818813810781908992 for some tips.

You should be able to upgrade `apisauce` to 0.8.0 without any stress.

**Comment by novotnej** [comment]
upgraded apisauce to 0.8.0 and still the same thing..

**Comment by skellock** [comment]
Don't forget to triple backtick your comments here.

```json
{
  "hello": "there"
}
```

![image](https://cloud.githubusercontent.com/assets/68273/22649137/af989d30-ec47-11e6-998d-c17549853c53.png)

**Comment by skellock** [comment]
I'd love to see the full response object.  Are you able to run this in Reactotron or Chrome Debugger so we can see the full request?  (don't forget to xxxxx out any sensitive creds before posting here)

**Comment by novotnej** [comment]
aaaah.. I finally got to the bottom of it, kinda.. the data: "GET" was actually what the server responded, when it was accessed using unsupported method.. 

so the problem now is - why does this request get sent as GET, instead of POST? 

can't run reactotron, it's a bit troublesome on Linux I'm afraid :/ but here's what I see:
![screenshot from 2017-02-06 14 51 00](https://cloud.githubusercontent.com/assets/3701992/22649576/d7b09ae6-ec7b-11e6-9693-634f599cb5de.png)

**Comment by skellock** [comment]
The method is set to `post` though.

![image](https://cloud.githubusercontent.com/assets/68273/22649715/36f114e0-ec4a-11e6-89f8-9ff2cd940acd.png)

Do you think that your server might be expecting `POST` instead of `post`?

And that URL is the same one you're using in postman eh?

**Comment by novotnej** [comment]
ok did some digging around on the server side. 
in the app I was using the non-www version, which does re-direct to the www. version. 

which is fine for GET and apparently it is default behavior to send a GET request to the redirected site instead of sending the same POST request, but to a different URL.. 

Well, sorry for wasting your time with this, but at least it pointed me in the right direction, I would've been looking for this for a while... :D
