### ISSUE TITLE
Upload progress handler for post requests

### ISSUE THREAD

**Issue by dcgoss** [skellock/apisauce#59]
For a post request it would be a great feature to be able to see the upload progress. Attaching some kind of handler to a request seems like the right way to do it: `(progressValue) => do stuff`
`api.post('url', data, (progressValue) => do stuff)`

From the Axios docs:

> // `onUploadProgress` allows handling of progress events for uploads
>   `onUploadProgress: function (progressEvent) {
>     // Do whatever you want with the native progress event
>   }`

**Comment by skellock** [comment]
You can do this now.  The 3rd parameter of post is handed right over to axios.  So this would be something like:

```js
api.post('url', data, { onUploadProgress: value => stuff(value) })
```

**Comment by ravirupareliya** [comment]
It is showing value as 

    {"type":"progress","target":{},"currentTarget":{},"eventPhase":2,"bubbles":false,"cancelable":false,"timeStamp":1496820159231,"isTrusted":false}

Where can i get progressCount or percentage?

**Comment by skellock** [comment]
It should have `loaded` and `total` If it is measurable. (see https://developer.mozilla.org/en/docs/Web/API/ProgressEvent)

What browser/environment are you using?

**Comment by ravirupareliya** [comment]
I am using it with React-Native.

Yes `loaded` and `total` worked for me. It is just not showing in JsonObject but i can use it directly like `progress.loaded` and `progress.total`

**Comment by skellock** [comment]
They might be getters and not iterable properties then.  Glad it's working!

**Comment by ProxyJoshua** [comment]
@skellock How should I declare `value` type in typescript?

**Comment by chakrihacker** [comment]
Hey, it's better not to tag, just a suggestion.

Secondly, I didn't understand the context of the `value`, can you be more specific with some example?

**Comment by ProxyJoshua** [comment]
I solved my problem, I'm using typescript.

`onUploadProgress: (values: ProgressEvent) => handleNewProgress(values)`

I didn't knew the values type
