### ISSUE TITLE
Parallel request (?)

### ISSUE THREAD

**Issue by adrianha** [skellock/apisauce#60]
Hi @skellock ,
I'm facing an issue when i am fetching on first request and then fetching second request. its look like the second request is waiting for the first to be done. The second request is being called on another route. Imagine if you are on products page and currently fetching each product's price and then you press one of product and will be redirected into new page (product detail page). on the new page, you create another request to get product's detail data. Any idea about this?

**Comment by skellock** [comment]
Hello. 

There's nothing specifically written in apisauce or axios that would queue requests up like this.

I know in some browsers, they have a per-domain limit.   It used to be 2 connections per domain, but I haven't looked recently.  It's probably different per browser now.

Are you using React JS or React Native?  Sagas?

Could this be a server side queue or throttle?

**Comment by adrianha** [comment]
Im using it on react native and redux thunk for create async action. I think its not server side issue, theres no queue or throttle..

**Comment by skellock** [comment]
Are you able to place some log statements in? Both before & after your fetches?  With some timestamps?  And post 'em here?  I'd love to see the timing.

**Comment by adrianha** [comment]
Here's the screenshot attached.
**Fetching first & second request (1)**
![1](https://cloud.githubusercontent.com/assets/5382429/23099241/c3477912-f694-11e6-8702-4bff689d8b5d.png)
**Fetching first & second request (2)**
![2](https://cloud.githubusercontent.com/assets/5382429/23099242/c34b7a9e-f694-11e6-8bff-32d454ff230b.png)
**Fetching only second request**
![3](https://cloud.githubusercontent.com/assets/5382429/23099243/c34dbbba-f694-11e6-9864-7f2c4c0593fe.png)

**Comment by skellock** [comment]
You're kicking off 38 simultaneous requests!  iOS will only let you do 4 in parallel.

Are you able to change the API to support asking for multiple products at a time?

If not, you'll have to write a priority queue to allow your "requests" to get priority over your "batches".

**Comment by adrianha** [comment]
ah thanks @skellock , i dont know there are limitations on parallel request. Yes, i think i need to request better API support for this request. Great library by the way 👍

**Comment by skellock** [comment]
Thank you.  Glad it's useful.  Axios does the heavy lifting.  We just put a little extra on top.

**Comment by adrianha** [comment]
@skellock , is there any guide or API that can be used to write a priority queue for request?

**Comment by skellock** [comment]
https://github.com/sindresorhus/p-queue will do the trick.

Instead of calling `api.get('')` directly, your apisauce wrapper could add things to the queue instead.

**Comment by adrianha** [comment]
Thanks @skellock ! i will take a look.
