### ISSUE TITLE
Set mode: no-cors

### ISSUE THREAD

**Issue by Amurmurmur** [skellock/apisauce#66]
@skellock 
How can I set the mode to no-cors?

In fetch I would do it this way:
```
fetch('https://github.com/', {
    method: 'get',
    headers: {
        'Accept': 'application/json, text/plain, */*',
        'Content-Type': 'application/json'
    },
    mode: 'no-cors',
}))
```

How can I achieve similar thing with axios/apisauce

Thank you in advance.

**Comment by skellock** [comment]
I'm really not sure.  I've read up a bit on this recently and found it very confusing how it worked.  I would love some pointers if you make it work.

**Comment by Amurmurmur** [comment]
@skellock Just managed to make it work.

I had to set Access-Control-Allow-Origin on the server side, so that the server return the header, otherwise the axios/apisauce will always return NETWORK_ERROR aka:

```
XMLHttpRequest cannot load https://serveraddress. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
```
However with the mode set to no-cors in my post above, fetch works, seems like axios/apisauce dont pass mode to the fetch/XMLHTTPRequest.

Hope this helps 👍

**Comment by skellock** [comment]
Thanks for the tips!

Are you on the browser or React Native?

**Comment by Amurmurmur** [comment]
@skellock 
I've used apisauce with react-native, and currently using it with the browser too(Chrome more specifically).

With react-native apisauce works like a charm, I can only say it is so amazing and comfortable and declarative 👍

**Comment by markusguenther** [comment]
@Amurmurmur Know that is closed but what did you change on server side to make this run?

Thanks for the question itself :)
