### ISSUE TITLE
Axios auth config not exposed in apisouce

### ISSUE THREAD

**Issue by gwest7** [skellock/apisauce#67]
I want to set basic auth on axios requests using its `auth` config property. Username and password (used for basic auth) is not know at the time of creation so it can't be set then. What is the solution so that I don't have to set the `Authorization` header myself?

**Comment by gwest7** [comment]
Ok, so far I just make a second apisouce instance once authenticated.

**Comment by skellock** [comment]
`.setHeader('Authorization', 'something')`
