### ISSUE TITLE
Hi, I want to help to continue using your package

### ISSUE THREAD

**Issue by cloud-walker** [skellock/apisauce#69]
Hi @skellock, I'm a front-end dev from [Wanderio](https://www.wanderio.com/) and I'm using your package since this summer.

I find your package really useful to isolate the API calls of my application, so I wish to continue use it.

But recently I had some trouble with it, so I will try to help you!

I will open some issues about each topic so we can tackle them separately, thanks in advance!

**Comment by skellock** [comment]
Thanks!
