### ISSUE TITLE
Is babel-preset-stage-0 really needed?

### ISSUE THREAD

**Issue by cloud-walker** [skellock/apisauce#70]
<img width="323" alt="screen shot 2017-03-16 at 08 33 08" src="https://cloud.githubusercontent.com/assets/1144075/23986189/37b6d2b0-0a23-11e7-9380-4dc50cd8d123.png">

Maybe we can switch to a more stable preset (like stage-2 or stage-3).

**Comment by skellock** [comment]
Yes.  We could definitely switch to a higher stage.  Thanks for pointing this out.

**Comment by cloud-walker** [comment]
Based on #75 we don't need stage-3 either because async-to-generator-transform will be introduced, I think we can just close this issue and wait for the `fast-async` PR

**Comment by skellock** [comment]
Beautiful!
