### ISSUE TITLE
Webpack bundle size and ramda redundance

### ISSUE THREAD

**Issue by cloud-walker** [skellock/apisauce#71]
My current apisauce version is 0.6 and I can't upgrade it for another issue that I will open later, maybe this issue is already solved..

This is the size of my main bundle external packages
<img width="695" alt="screen shot 2017-03-16 at 08 35 46" src="https://cloud.githubusercontent.com/assets/1144075/23986278/9ef44ade-0a23-11e7-9ea6-b12a59c7d52f.png">

As you may notice I have a problem with ramda.js, the library is first in terms of size, and I bet because I import the whole library without tree-shaking/picking only the functions I really use in the application..

But I also see a double ramda depedency coming from apisauce!

**Comment by skellock** [comment]
Woah.  Haha.  Ya we can optimize this for sure.

**Comment by cloud-walker** [comment]
If you need to experiment using webpack, I use:

- webpack 2
- [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) to analyze the bundles

**Comment by skellock** [comment]
I dropped ramdasauce as a dependency, so we shouldn't have double ramda action.
