### ISSUE TITLE
Upgrading to 0.10 breaks chrome 34

### ISSUE THREAD

**Issue by cloud-walker** [skellock/apisauce#72]
This is the error
<img width="901" alt="screen shot 2017-03-16 at 08 53 03" src="https://cloud.githubusercontent.com/assets/1144075/23986778/35b7c4da-0a26-11e7-94a7-7808545edf61.png">

And I think the bug come from `regenerator-runtime` dependency used by the package to support async/await.

I'm not sure which is the best solution:
- try to use another solution to support async/await (fast-async? As you already mentioned on #58 ?)
- maybe I should simply polyfill the `symbol.toStringTag` thing? 
- we should open an issue on the regenerator-runtime package?

**Comment by skellock** [comment]
Ya it's my preference to use fast-async and ditch the regenerator-runtime entirely.
