### ISSUE TITLE
Setting Default Headers After Create

### ISSUE THREAD

**Issue by skellock** [skellock/apisauce#8]
You can set the default headers when you call `create()`.  Yay.

But if you want to change that after that call, you have to reach into the `axiosInstance.defaults.headers` object to mutate it.

Let's provide a nicer way for this.

**Comment by duketwo** [comment]
+1

**Comment by skellock** [comment]
It's the third parameter.

api.post('/users', {name: 'duke'}, {headers: {'x-hello': 'world'}})

I'll document this better.

**Comment by gaboelnuevo** [comment]
:+1:    for this enhancement

I need to do something like this:

api.post('/users/login',  {
    "email": "foo@bar.com",
    "password": "bar"
}).then((response) => api.overrideConfig({
		headers: {'Authorization': response.data.token}
	})
);

**Comment by GantMan** [comment]
Hah, I should have dug through issues, I just solved this on my side.  Agreed, exposing axiosInstance is not nice.

**Comment by GantMan** [comment]
Also worth noting, axios docs has 
`instance.defaults.headers.common['Authorization']` as a possibility in their latest.  But this doesn't work with the version associated in latest apisauce.

**Comment by skellock** [comment]
I expose axios exactly for this reason.  I didn't want to trap Axios' abilities behind our API.

Common features like this exactly what apisauce should do for us, you're right.

I will bump the version this weekend!

Thanks dude!

**Comment by GantMan** [comment]
Sweeeeet!  yeah, having it exposed is good for work-arounds.

**Comment by skellock** [comment]
Now supported with 0.3.0 just released.

```js
api.setHeader('Authorization', 'new stuff')
api.setHeaders({ 'X-Fun': 1, 'X-More-Fun': 69 })
```
More details in #20

**Comment by ningo-agilityio** [comment]
I already used `setHeader` but it was refreshed after browser refresh.

**Comment by ryanlntn** [comment]
@ningo-agilityio That would be expected behavior as an in memory object state would be reset on a browser refresh. You'll need to store any tokens you might want to hold on to in a persistent store like local storage and restore them in a `document.onreadystatechange` callback. For example:

```
document.onreadystatechange = () => {
  if (document.readyState === 'complete') {
    const token = localStorage.getItem('authToken')
    api.setHeader('Authorization', token)
  }
}
```
