### ISSUE TITLE
Avoiding ssl cert verification

### ISSUE THREAD

**Issue by pablotango** [skellock/apisauce#87]
I'm using apisauce in React Native app to connect to an external api that is not on my own. 
I'm working with a dev environment that i cannot touch and i would like to ignore the cert error to test the connection.
There is a way to ignore invalid certificates?

**Comment by skellock** [comment]
That's a really good question.

A quick google search turned up this:

https://github.com/mzabriskie/axios/issues/535

If this works, I'd be happy to add support to the library to make it a little easier to do.

**Comment by pablotango** [comment]
i was reading that workaround too, but apparently is not working with axios either (reading some answers in the same thread)

**Comment by skellock** [comment]
Also, react native is a different beast sometimes.  They wrote their own HTTPXMLRequest wrapper, and they just might not support all pass-throughs.  (because they have another platform-specific layer for ios & android they have to talk to).

**Comment by skellock** [comment]
For example:  http://stackoverflow.com/questions/36289125/react-native-fetch-from-https-server-with-self-signed-certificate

**Comment by pablotango** [comment]
Apparently no solution there... only some change in xcode to make it works, but not for android... so... i think we can close the issue... or leaving it open for people looking for the same issue...

thanks anyway for your fast answer! 

pd... apisauce is great :)

**Comment by skellock** [comment]
There's probably a way to do this too in Android.

For example: http://stackoverflow.com/questions/25509296/trusting-all-certificates-with-okhttp

And why am I not suprised to see this thing called a Manager and Factory.  Haha.

Thanks for the kind words.  I think I'll close this only because we can't fix it at this level.
