### ISSUE TITLE
post with form-data

### ISSUE THREAD

**Issue by jkolbe** [skellock/apisauce#88]
Hi,

I am having difficulty passing multiple variables to the post method using apisauce.
I am getting a response with data.error which indicates that it didn't receive the params

```
import apisauce from 'apisauce'

const create = (baseURL = 'http://prod.karma.vote/api/') => {
	const api = apisauce.create({
    	baseURL,
    	headers: {
    		'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8',
    		'Accept' : '*/*'
    	}
  	})

  	if (__DEV__ && console.tron) {
    	api.addMonitor(console.tron.apisauce)
  	}


  	const login = () => {
  		return api.post('login', {
        {
    			email: 'xxr@xx.xx',  firstName: 'XX', 
    			lastName: 'XX',  profilePicUrl: 'example.png',
    			'device.facebookId': '1234567', 'device.token': '',
  			 'device.platform': ''
        });
    
  	}

	return {
		login
	}
}

export default {
  create
}
```

**Comment by skellock** [comment]
You'll want to make sure you use `new FormData()` and add your data like that.  Adding fields like this won't be detected server-side.

[See this](https://github.com/mzabriskie/axios/blob/322be107301c5c725b13e3c0c00108e55655f540/examples/upload/index.html#L25) for a brief overview.
