### ISSUE TITLE
Dealing With Null Parameters

### ISSUE THREAD

**Issue by skellock** [skellock/apisauce#9]
The QSV parsing is taking objects that are `null` and transforming them into the string "null".  That's not cool.

**Comment by kevinvangelder** [comment]
Does this only apply to URL parameters or JSON bodies as well?

**Comment by skellock** [comment]
The `null`s should be fine, but I'll test that as well when I'm fixing up the QSV's.

Thanks!

**Comment by skellock** [comment]
https://github.com/skellock/apisauce/commit/277c701eab186f69afb5d5eb8abfb04cf4501f4b

I can't seem to reproduce this behaviour.  Hmm... i wonder if this is different on React Native?
