### ISSUE TITLE
Metadata part is too large.

### ISSUE THREAD

**Issue by caraquista** [skellock/apisauce#92]
Hi, firts sorry for my english is so bad... i write here because i'm using that library to upload files to Google Bucket, when the files are small it works very good, but large files throws that error:

{
config:Object
data:"Metadata part is too large."
duration:1451
headers:Object
ok:false
problem:"CLIENT_ERROR"
status:400
}

the call is like:

const file = {
    uri:response.file.uri,          
    type:response.file.type ? response.file.type : response["Content-Type"]
  }

  data.append('signature', response.signature)
  data.append('policy', response.policy)
  data.append('key', response.key)
  data.append('bucket', response.bucket)
  data.append('GoogleAccessId', response.GoogleAccessId)
  data.append('Content-Type', response["Content-Type"])
  data.append('file', file);

  return postUrl.post('/', data) // postUrl is a instance of apiSauce

So, there are some mode to indicate to apisauce who the data is large or set it a max size of file.

Again sorry for my bad english.

**Comment by skellock** [comment]
The 400 error is something that's returned from the server.  Sounds like you might be sending too much data?  I haven't looked at the source code but I don't think there's any limits on the axios/client end of things.
