### ISSUE TITLE
Add a way to delete headers

### ISSUE THREAD

**Issue by jkeam** [skellock/apisauce#94]
Sometimes you set a header but later want to remove it.  For example, an Authentication header or something.  Would be nice to have a way to do this.

**Comment by joaofranca** [comment]
I've been doing it like this. Doesn't this work?

```
const api = apisauce.create({
    ...
});

...

delete api.headers['Authorization']
```

**Comment by jjercx** [comment]
yeah, that works  👆🏽

**Comment by blaues0cke** [comment]
FYI: This works but triggers `no-param-reassign` from eslint. Would be nice to be also able to do this using a method.

**Comment by jkeam** [comment]
Does this method work for you?

https://github.com/infinitered/apisauce/pull/95/commits/11235d28a9adb9e911d74cd7ee3ee12c6fff2228

**Comment by Nayan-nandakumar** [comment]
apiClient.deleteHeader('Authorization');  this wi;; work
