### ISSUE TITLE
Error while using nocks 

### ISSUE THREAD

**Issue by ashik94vc** [skellock/apisauce#96]
Hey, 
I am receiving the following error when I'm trying to post a multipart form data from nock.

```yaml
Failed: Cannot read property 'status' of undefined
TypeError: Cannot read property 'status' of undefined
    at /Users/vcashik/workspace/ReactNativeApp/node_modules/apisauce/dist/apisauce.js:205:49
    at /Users/vcashik/workspace/ReactNativeApp/node_modules/apisauce/node_modules/ramda/src/cond.js:42:30
    at /Users/vcashik/workspace/ReactNativeApp/node_modules/apisauce/node_modules/ramda/src/internal/_arity.js:5:45
    at getProblemFromError (/Users/vcashik/workspace/ReactNativeApp/node_modules/apisauce/dist/apisauce.js:206:186)
    at convertResponse (/Users/vcashik/workspace/ReactNativeApp/node_modules/apisauce/dist/apisauce.js:174:29)
    at /Users/vcashik/workspace/ReactNativeApp/node_modules/apisauce/node_modules/ramda/src/internal/_createPartialApplicator.js:8:17
    at /Users/vcashik/workspace/ReactNativeApp/node_modules/apisauce/node_modules/ramda/src/internal/_arity.js:5:45
    at /Users/vcashik/workspace/ReactNativeApp/node_modules/apisauce/node_modules/ramda/src/internal/_pipe.js:3:27
    at /Users/vcashik/workspace/ReactNativeApp/node_modules/apisauce/node_modules/ramda/src/internal/_arity.js:5:45
    at tryCallOne (/Users/vcashik/workspace/ReactNativeApp/node_modules/promise/lib/core.js:37:12)
```

This error is weird and I am breaking my head for a day on this. I hope that someone can help before I fix my head.

**Comment by skellock** [comment]
Ah.  One of the things that axios does is attaches the `response` object to the `error`.

Are you getting this when mocking errors by any chance?  If so, you'll need to attach a response to the error object.

Here's where I believe this is going off the rails:

https://github.com/skellock/apisauce/blob/master/lib/apisauce.js#L296

**Comment by ashik94vc** [comment]
Yeah, exactly. This is the place where it went wrong. I got this while mocking http request. For some reason, the request went haywire as `nock` couldn't match the request. This caused the request to fail without a status code, I believe.

**Comment by skellock** [comment]
They recently (0.14? 0.15?) changed the interface to this in axios.   I've never used nock before, but is it something where you can control setting the error?

**Comment by ashik94vc** [comment]
Nock is completely different. It intercepts http requests to give a mock response right ? Albeit it should not cause this error. Sure it did set response in error to undefined. Shouldn't​ this be handled ?

**Comment by skellock** [comment]
I see your point.  I think this could be caught.  

Keep in mind your replacing part of the HTTP chain and replacing it with something unexpected which is causing axios to behave differently.

I'd accept a PR though to catch this case.  If you want to share an example of the code you're using, I could probably do it myself too.

**Comment by ashik94vc** [comment]
Hey, I just added a simple validation in `getProblemFromError()` to check whether the error has a response or not.

**Comment by budowski** [comment]
(For anyone getting from Google and trying to make `apisauce` work with `nock` in React Native:
```
jest.mock( "apisauce", ( ) => ( {
  create: (config) => {
    let axiosInstance = jest.requireActual('axios').create(config);
    const apisauce = jest.requireActual('apisauce');
    return apisauce.create({ ...config, axiosInstance });
  }
} ) );
```

We basically override `apisauce.create` method, add forcefully add an `axios` instance -> which then allows us to use `nock`.
